### ISSUE TITLE
Forgot Password and Invite User(s)

### ISSUE THREAD

**Issue by RadhikaPPatel** [buildlyio/buildly-react-template#12]
1. **_Forgot Password_** is not yet set up in the code.
2. **_Invite User(s)_** from the User management right now has a lot of unwanted code. It only sends the invite email to a single email address right now. Instead, it should be able to send it to 1 or multiple email addresses.

**Comment by andrewshortall** [comment]
I'll implement forgot password when I get a chance. The invite users issue seems to be a backend problem. The comma separated values are sent correctly.

**Comment by RadhikaPPatel** [comment]
1. Right now the invite user form sends emails as ['abc@abc.com, xyz@xyz.com, uvw@uvw.co'].
2. Instead it should be like ['abc@abc.com', 'xyz@xyz.com', 'uvw@uvw.com']. 
BE handles it in option 2.
